#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>

void copy_file(int in_fd, int out_fd) {
    char buffer[4096];
    size_t read_bytes;
    while ((read_bytes = read(in_fd, buffer, 4096)) > 0) {
        write(out_fd, buffer, read_bytes);
    }
}

int main(int argc, char *argv[]) {
    int in_fd = open("file1", O_RDONLY, S_IRUSR | S_IWUSR);
    int out_fd = open("file2", O_WRONLY | O_CREAT | O_TRUNC, S_IRUSR | S_IWUSR);
    copy_file(in_fd, out_fd);
    close(in_fd);
    close(out_fd);
    return 0;
}
/*
123
zxcvbnm
12345678
yfyv  f ftidf tf ufuyy
buib

1234567.

zxcvbnm,.lkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdt
fyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe3
4567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjh
gfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghuj
koiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrd
tfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe
34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkj
hgfdsawesrdtfyghujkoi345
67uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkj345
67uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjk
j34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjk
j34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjk
j34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjk
j34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjk
juyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghu
jkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesr
dtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdew
e34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjk
jhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfygh
ujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhilkjhgfdewe34567uioasdfghjkjhgfdsawesrdtfyghujkoiuyftdrseawesrdtfyguhi
hui
*/
